# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 390)
        Form.setStyleSheet("/* === GLOBAL WIDGET BACKGROUND === */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 1,\n"
"        stop: 0 #fdfdfd,\n"
"        stop: 0.5 #fceabb,\n"
"        stop: 1 #e0f7fa\n"
"    );\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    font-size: 12pt;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #222;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    qproperty-alignment: 'AlignCenter';\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #005a9e;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #004578;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 6px;\n"
"    font-weight: bold;\n"
"    color: #444;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 300, 31))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")

        self.Calculer = QtWidgets.QPushButton(Form)
        self.Calculer.setGeometry(QtCore.QRect(600, 100, 120, 41))
        self.Calculer.setObjectName("Calculer")

        self.Reset = QtWidgets.QPushButton(Form)
        self.Reset.setGeometry(QtCore.QRect(600, 150, 120, 41))
        self.Reset.setObjectName("Reset")

        self.lineEdit_4 = QtWidgets.QTextEdit(Form)
        self.lineEdit_4.setWordWrapMode(QtGui.QTextOption.WordWrap)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 260, 800, 90))
        self.lineEdit_4.setStyleSheet("background-color: rgb(196, 233, 236);")
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(310, 70, 135, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)

        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(30, 70, 260, 121))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculatrice Binaire"))
        self.label.setText(_translate("Form", "Calculatrice Binaire"))
        self.Calculer.setText(_translate("Form", "Calculer"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.label_2.setText(_translate("Form", "Premier opérande"))
        self.label_4.setText(_translate("Form", "Opérateur:+, -, *, /, |, & , ^ "))
        self.label_3.setText(_translate("Form", "Deuxième opérande"))

















